input_uname_desktop = "xpath@@//input[@id='Username']"
input_pwd_desktop = "xpath@@//input[@id='Password']"
forgot_pwd_link_desktop = "xpath@@//a[contains(text(),'Forgot Password?')]"
btn_login_fb_desktop = "xpath@@//button/p[contains(text(),'Login with Facebook')]"
login_btn_desktop = "xpath@@//p[contains(text(),'have an account?')]/following::div/p[.//text()='Login']"
error_img_desktop = "xpath@@//p[contains(@class,'Login_hasError')]"
input_uname_mobile = "xpath@@//input[@id='Username']"
input_pwd_mobile = "xpath@@//input[@id='Password']"
forgot_pwd_link_mobile = "xpath@@//a[contains(text(),'Forgot Password?')]"
btn_login_fb_mobile = "xpath@@//button/p[contains(text(),'Login with Facebook')]"
login_btn_mobile = "xpath@@//*[contains(@class,'Login_actionsContainer')]//preceding-sibling::" \
    "div[contains(@class,'Login_buttonContainer')]/p"
