input_email_desktop = "xpath@@//input[@id='Email address']"
input_password_desktop = "xpath@@//input[@id='Password']"
confirm_password_desktop = "xpath@@//input[@id='Confirm Password']"
create_account_btn_desktop = "xpath@@//*[contains(@class,'CreateAccount_button')]/p"
already_login_btn_desktop = "xpath@@//p[contains(text(),'Already have an account?')]/a[@href='/login']"
sign_up_facebook_btn_desktop = "xpath@@//p[contains(text(),'Signup with Facebook')]/ancestor::button"
input_email_mobile = "xpath@@//input[@id='Email address']"
input_password_mobile = "xpath@@//input[@id='Password']"
confirm_password_mobile = "xpath@@//input[@id='Confirm Password']"
create_account_btn_mobile = "xpath@@//*[contains(@class,'CreateAccount_buttonContainer')]/p"
already_login_btn_mobile = "xpath@@//p[contains(text(),'Already have an account?')]/a[@href='/login']"
sign_up_facebook_btn_mobile = "xpath@@//p[contains(text(),'Signup with Facebook')]/ancestor::button"
